CREATE TABLE IF NOT EXISTS public.failed_broker_event (
	id VARCHAR(50) PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
	status VARCHAR(50) NOT NULL,
	topic VARCHAR(50) NOT NULL,
	data JSONB NOT NULL,
	error TEXT NOT NULL
);